const colors = {
  primary: '#35CDFA',
  primaryLight: '#35CDFA',
  primaryDark: '#00B1EC',
  primaryGradientStart: '#5ED8FC',
  primaryGradientEnd: '#35CDFA',
  secondaryGradientStart: '#FFDF00',
  secondaryGradientEnd: '#FF52A8',
  profileGradientStart: '#FE9F7C',
  profileGradientEnd: '#FDB167',
  secondary: '#7A7BE6',
  secondaryButtonText: '#ffffff',
  primaryButtonText: '#ffffff',
  introText: '#ffffff',
  grey: '#acacac',
  gray: '#5f5f5f',
  darkGray: '#4d4d4d',
  darkGrayTransparent: '#4d4d4d4d',
  lightGray: '#9b9b9b',
  lightGrayTransparent: '#9b9b9b9b',
  white: '#ffffff',
  blue: '#5A81F7',
  bluish: '#F1F1F7',
  black: '#000000',
  green: '#6DD0A3',
  yellow: '#ffc247',
  labelOne: '#FDCB67',
  labelTwo: '#FE8B7C',
  textInputColor: '#ffffff',
  textInputBackgroundColor: '#FFFFFF2B'
};

export default colors;
